version: "3.4"
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    restart: always
    ports:
      - '27017:27017'
    volumes:
      # if you wish to setup additional user accounts specific per DB or with different roles you can use following entry point
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    # no --auth is needed here as presence of username and password add this option automatically

  spring-app:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    restart: always
    ports:
      - "8080:8080"
      # mount dir to save data backup
    volumes:
      - /Users/dabeeovina/Documents/MySelf/crawler-extension/crawler:/home
    environment:
      - SPRING_DATASOURCE_URL=mongodb://user:pass@mongo:27017/crawler
      - SPRING_MONGO_DATABASE=crawler
      - SPRING_APP_BACKUP_DIR=/home
      - SPRING_APP_DIR=/Users/dabeeovina/Documents/MySelf/crawler-extension
      - SPRING_APP_DIR=python C:\Users\hungh\OneDrive\Desktop\Myself\crawler-extension\autorun.py